<a href="https://colab.research.google.com/github/Nivoter/ML/blob/main/PR01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Задание 1

Объясните результат операции:

In [17]:
print(arr[:5:-2])

[10, 8]


Если задан отрицательный шаг, то index_start и index_end меняются местами, следовательно выполнена следующая запись [index_end:index_start:-2] 

Также, в случае незаданного index_end он равняется индексу конца массива

Поэтому эта команда и вывела элементы с конца до 5 с шагом 2


Задание 2

Получите перевернутый список:

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
data = list(range(10))
print(data)

# TODO - [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
print(data[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Задание 3

Получите массив без первого и двух последних элементов:

In [20]:
data = list(range(10))
print(data)

# TODO - [1, 2, 3, 4, 5, 6, 7]
print(data[1:8])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7]



Задание 4

Получите массив без крайних рядов и колонок (по одной с каждой стороны)

In [29]:
data = np.random.randint(low=0, high=10, size=(5, 6))
print(data)
print('/////////')
print(data[1:5,1:5])
# TODO - центральная часть массива размером (4, 5)

[[2 4 8 1 1 3]
 [9 1 0 6 1 6]
 [4 3 4 1 0 1]
 [8 8 1 5 5 5]
 [4 9 3 9 4 5]]
/////////
[[1 0 6 1]
 [3 4 1 0]
 [8 1 5 5]
 [9 3 9 4]]


Задание 5

Произведите перемешивание колонок с помощью функции numpy.random.permutation():

In [51]:

data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)

# TODO - такой же массив, но со случайной перестановкой колонок
print('/////////')

print(data[:,np.random.permutation(6)])

[[0 4 0 3 7 5]
 [3 9 7 3 4 3]
 [2 4 9 9 3 1]]
/////////
[[5 4 7 3 0 0]
 [3 9 4 3 7 3]
 [1 4 3 9 9 2]]



Задание 6

Определите, имеется ли хотя бы одно значение больше пяти и меньше восьми в массиве:

In [61]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

# TODO - определить, имеется ли в массиве хотя бы один элемент, 
#           отвечающий условию больше пяти и меньше восьми

np.any((arr>5)&(arr<8))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


True

Задание 7

Напишите операцию получения суммы элементов по всем стобцам:

In [63]:

data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)

# TODO - вектор сумм элементов по каждому столбцу
data1 = np.sum(data,axis=0)
print(data1)

[[2 0 1 2 4 2]
 [4 0 3 2 3 1]
 [1 0 2 2 1 3]]
[7 0 6 6 8 6]


Задание 8

Объедините три массива вдоль колонок:

In [73]:

x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(x)
print(y)
print(z)

# TODO - получите объединенный массив:
# [[ 0  1  2  0  1  2  3  0  1  2  3  4]
#  [ 3  4  5  4  5  6  7  5  6  7  8  9]
#  [ 6  7  8  8  9 10 11 10 11 12 13 14]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [76]:
print(np.concatenate((x, y, z), axis=1))

[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]



Задание 9

Напишите реализацию добавления стобца единиц к матрице слева:

In [102]:
x = np.arange(1, 10).reshape((3, 3))
print(x)

# TODO - получить матрицу со столбцом единиц слева
# [[1 1 2 3]
#  [1 4 5 6]
#  [1 7 8 9]]
y = np.ones([3,1],dtype = int)
print(y)
print(np.concatenate((y,x),axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [1]
 [1]]
[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]



Задание 10

По такому же принципу именования найдите функцию, которая возвращает индекс максимального/минимального (в завимости от варианта) элемента в массиве.

Воспользуйтесь найденной функцией и найдите индексы максимальных элементов в каждом столбце 2D матрицы:

In [174]:
arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])

print(arr)

# TODO - напишите код поиска индексов максимальных/минимальных 
#           элементов в массиве по столбцам: [0 2 3 3 1]/[2 0 1 1 0]
print('///////')
print(np.argmax(arr,axis = 0))
print(np.argmin(arr,axis = 0))

[[11 -1  1  3  5]
 [ 6  1  0 -1 10]
 [ 1  3  2  3  6]
 [ 5  2  7  8  9]]
///////
[0 2 3 3 1]
[2 0 1 1 0]



Задание 11

Напишите код сортировки массива по столбцам:

In [120]:
arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])
print(arr)
print('///////')
print(np.sort(arr,axis = 0))
# TODO - напишите код сортировки:
# [[ 1  2  0 -1  5]
#  [ 5  2  1  3  5]
#  [ 6  2  2  3  9]
#  [11  3  7  8 10]]

[[11  2  1  3  5]
 [ 6  2  0 -1 10]
 [ 1  3  2  3  5]
 [ 5  2  7  8  9]]
///////
[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


Задачки

Создайте массив, состоящий из случайных элементов в диапазоне $[-10; 20]$ размером $(5, 7)$:

In [123]:
# TODO - создайте массив со случайными целочисленными элементами
print(np.random.randint(low = -10, high = 20, size = [5, 7]))

[[ -2  18   2  14   4 -10  -2]
 [ 16   4   7  14   8   6  -1]
 [ 13  10  10  10 -10   4   5]
 [  7  -3  -1   5  19   0  -7]
 [ 17  -9 -10  18  11  14  16]]



Добавьте границу в виде нулей со всех сторон 2D массива:

In [142]:
data = np.arange(1, 16).reshape((3, 5))
print(data)

# TODO - реализуйте добавление нулей со всех сторон массива:
# [[ 0  0  0  0  0  0  0]
#  [ 0  1  2  3  4  5  0]
#  [ 0  6  7  8  9 10  0]
#  [ 0 11 12 13 14 15  0]
#  [ 0  0  0  0  0  0  0]]
np.concatenate?
arr = np.concatenate((np.zeros([3,1],dtype = int),data),axis =1)
arr = np.concatenate((arr,np.zeros([3,1],dtype = int)),axis =1)
arr = np.concatenate((np.zeros([1,7],dtype = int),arr),axis =0)
arr = np.concatenate((arr,np.zeros([1,7],dtype = int)),axis =0)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]



Разберитесь с функцией np.clip() и произведите ограничение массива, чтобы в нем значения были не более шести и не менее двух:

In [199]:

data = np.arange(1, 16).reshape((3, 5))
print(data)

# TODO - ограничьте значения массива
# [[2 2 3 4 5]
#  [6 6 6 6 6]
#  [6 6 6 6 6]]
print('//////////////////')
print(np.clip(data,2,6))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
//////////////////
[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]



Произведите модификацию массива так, чтобы значение в колонке результата соответствовало исходному значению, возведенному в степень индекса колонки

In [198]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)

# TODO - возведите значения в колонках в степень индекса колонки
# [[ 1  2  4  8 16]
#  [ 1  2  4  8 16]
#  [ 1  2  4  8 16]]
print('//////////////////')
print(np.power(data,np.arange(5)))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
//////////////////
[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


Умножьте каждую колонку на ее индекс:

In [197]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)

# TODO - Умножьте каждый столбец на свой индекс
# [[0 2 4 6 8]
#  [0 2 4 6 8]
#  [0 2 4 6 8]]
print('//////////////////')
print(data*np.arange(5))


[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
//////////////////
[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]



Умножьте каждый четный ряд в матрице на вектор:

In [196]:
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
print(data)

# TODO - умножьте каждый четный ряд в матрице на вектор
# [[ 1  2  1  2]
#  [ 2  2  2  2]
#  [ 3  6  3  6]
#  [ 4  4  4  4]
#  [ 5 10  5 10]
#  [ 6  6  6  6]
#  [ 7 14  7 14]]
i = 0
print('//////////////////')
for i in range(7):
  if np.mod(i,2) == 0:
    data[i,:] = data[i,:]*vec
print(data)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
//////////////////
[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]



Определите индексы двух наибольших элементов в матрице по каждому ряду:

In [195]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)

# TODO - определите индексы двух наибольших элементов по каждому ряду
# [[4 1]
#  [1 2]
#  [3 1]
#  [5 3]]
print('//////////////////')
print(np.flip(np.argsort(data),axis = 1)[:,0:2])


[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
//////////////////
[[4 1]
 [1 2]
 [3 1]
 [5 3]]



Выберите две случайные колонки из массива:

In [210]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)

# TODO - выберите случайные две колонки из массива
# *Например,
# [[22  8]
#  [25 15]
#  [16  9]
#  [24 40]]

print(data[:,np.random.randint(low = 0, high = 5, size = [1,2])])

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
[[[22  2]]

 [[25 23]]

 [[16  9]]

 [[24 24]]]



Создайте массив размером $(10, 3)$, который состоит из повторяющихся рядов исходного массива:

In [232]:
data = np.arange(9).reshape(3, 3)
print(data)

# TODO - создайте массив из повторяющихся рядов размером (10, 3)
# *Например,
# [[3 4 5]
#  [6 7 8]
#  [0 1 2]
#  [6 7 8]
#  [3 4 5]
#  [6 7 8]
#  [6 7 8]
#  [6 7 8]
#  [6 7 8]
#  [0 1 2]]
print('///////////////////')
y  = data[0:2,:]
newdata = np.concatenate((data, y), axis =0 )
newdata = np.concatenate((newdata, newdata), axis =0 )
print(np.random.permutation(newdata))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
///////////////////
[[6 7 8]
 [6 7 8]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [0 1 2]]



Соберите массив, состоящий из элементов 2й и 4й колонок и строк с 1й по 3ю:

In [241]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
# TODO - соберите матрицу из конкретных элементов массива
# [[23 22]
#  [ 9  0]
#  [33  7]]
newdata = np.array([[data[1,2], data[1,4]],
           [data[2,2], data[2,4]],
           [data[3,2], data[3,4]]])
print('/////////')
print(newdata)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
/////////
[[23 22]
 [ 9  0]
 [33  7]]



Инвертируйте порядок элементов в последних двух колонках:

In [252]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
# TODO - инвертируйте порядок последних двух колонок
# [[20 22  2 14  3 40]
#  [ 7 25 23  3  7  6]
#  [ 8 16  9 22  0  9]
#  [14  9 33 21 22 15]
#  [ 4 24 24 28 25  8]]
print('/////////')
data1 = np.flip(data[:,4:6],axis = 0)
data2 = data
data2[:,4:6] = data1
print(data2)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
/////////
[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]
