<a href="https://colab.research.google.com/github/Nivoter/ML/blob/main/PR03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas==1.0.0

In [5]:

import pandas as pd
import numpy as np

Задание 1

Создайте фрейм с именами колонок 'col_1', 'col_2', 'col_3' и индексами по алфавиту ('A', 'B', 'C', ... или 'A', 'Б', 'В', ...).

In [13]:
# TODO
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)
df = pd.DataFrame(data = arr,index=['A','B','C','D','E'],columns=['col_1','col_2','col_3'])
df

[[9 1 8]
 [3 9 9]
 [8 5 5]
 [7 7 7]
 [3 2 9]]


col_1  col_2  col_3
A      9      1      8
B      3      9      9
C      8      5      5
D      7      7      7
E      3      2      9


Задание 2

Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только feature1 и feature3:

In [36]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df

feature1   feature2 feature3
A         0   0.000000   string
B         1   0.714286   string
C         2   1.428571   string
D         3   2.142857   string
E         4   2.857143   string
F         5   3.571429   string
G         6   4.285714   string
H         7   5.000000   string
I         8   5.714286   string
J         9   6.428571   string
K        10   7.142857   string
L        11   7.857143   string
M        12   8.571429   string
N        13   9.285714   string
O        14  10.000000   string

In [53]:
# TODO - выделите часть фрейма с помощью .loc[]
df.loc['C':'I', ['feature1','feature3']]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [70]:
# TODO - выделите часть фрейма с помощью .iloc[]
df.iloc[2:9,[0,2]]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

Задание 3

Выберите записи во фрейме, которые по признаку x1 имеют значение больше 3, а по признаку x3 - меньше 8.

In [75]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head()

x1  x2  x3
0   9   7   1
1   1   9   9
2   8   9   1
3   4   9   1
4   4   2   9

In [136]:
# TODO - отфильтровать фрейм по значениям признаков
mask = df[df['x1'] > 3]
mask = mask[mask['x3'] <8]
mask


x1  x2  x3
0    9   7   1
2    8   9   1
3    4   9   1
8    6   2   3
11   4   4   4
12   7   4   3

In [147]:
# TODO - отобразите только колонки x1 и x2 с учетом условий 
#           (используйте .loc[])
df.loc?
mask.loc[:,['x1','x2']]

x1  x2
0    9   7
2    8   9
3    4   9
8    6   2
11   4   4
12   7   4

Задание 4

С помощью метода DataFrame.query() получите записи, которые соответсвуют условию сравнения колонок $x1 &gt; x3$:

In [150]:
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   1   2   6
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0
5  -1   2   1
6   5   5   5

In [151]:

# TODO - Методом DataFrame.query() получить записи, удовлетворяющие условию
#           x1 > x3
df.query('x1 > x3')

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [153]:
# TODO - Сделать аналогичное действие, но уже с помощью условной индексации
df[df['x1']>df['x3']]

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0


Задание 5

Переименуйте индексы и колонки во фрейме

In [154]:

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   3   7   0
B   7   0   0
C   8   7   4
D   5   0   6
E   5   2   7

In [158]:

# TODO - переименуйте индексы [A, C] -> [indA, indC] 
#           и колонки [x1, x3] -> [new1, new3]
df.rename(
    index ={
        'A': 'indA',
        'C': 'indC'
    },
    columns={
        'x1': 'new1',
        'x3': 'new3' 
    },
    inplace = True
)
df

new1  x2  new3
indA     3   7     0
B        7   0     0
indC     8   7     4
D        5   0     6
E        5   2     7

Задание 6

Отфильруйте записи по строке, содержащейся в имени индекса (аргумент like):

In [160]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [163]:
# TODO - отфильтруйте по записям, должны остаться записи, 
#           индекс которых содержит слово "house"
df.filter(regex='house$',axis = 'index')


x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6