<a href="https://colab.research.google.com/github/Nivoter/ML/blob/main/PR03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas==1.0.0

In [5]:

import pandas as pd
import numpy as np

Задание 1

Создайте фрейм с именами колонок 'col_1', 'col_2', 'col_3' и индексами по алфавиту ('A', 'B', 'C', ... или 'A', 'Б', 'В', ...).

In [13]:
# TODO
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)
df = pd.DataFrame(data = arr,index=['A','B','C','D','E'],columns=['col_1','col_2','col_3'])
df

[[9 1 8]
 [3 9 9]
 [8 5 5]
 [7 7 7]
 [3 2 9]]


col_1  col_2  col_3
A      9      1      8
B      3      9      9
C      8      5      5
D      7      7      7
E      3      2      9


Задание 2

Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только feature1 и feature3:

In [36]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df

feature1   feature2 feature3
A         0   0.000000   string
B         1   0.714286   string
C         2   1.428571   string
D         3   2.142857   string
E         4   2.857143   string
F         5   3.571429   string
G         6   4.285714   string
H         7   5.000000   string
I         8   5.714286   string
J         9   6.428571   string
K        10   7.142857   string
L        11   7.857143   string
M        12   8.571429   string
N        13   9.285714   string
O        14  10.000000   string

In [53]:
# TODO - выделите часть фрейма с помощью .loc[]
df.loc['C':'I', ['feature1','feature3']]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [70]:
# TODO - выделите часть фрейма с помощью .iloc[]
df.iloc[2:9,[0,2]]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

Задание 3

Выберите записи во фрейме, которые по признаку x1 имеют значение больше 3, а по признаку x3 - меньше 8.

In [75]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head()

x1  x2  x3
0   9   7   1
1   1   9   9
2   8   9   1
3   4   9   1
4   4   2   9

In [136]:
# TODO - отфильтровать фрейм по значениям признаков
mask = df[df['x1'] > 3]
mask = mask[mask['x3'] <8]
mask


x1  x2  x3
0    9   7   1
2    8   9   1
3    4   9   1
8    6   2   3
11   4   4   4
12   7   4   3

In [147]:
# TODO - отобразите только колонки x1 и x2 с учетом условий 
#           (используйте .loc[])
df.loc?
mask.loc[:,['x1','x2']]

x1  x2
0    9   7
2    8   9
3    4   9
8    6   2
11   4   4
12   7   4

Задание 4

С помощью метода DataFrame.query() получите записи, которые соответсвуют условию сравнения колонок $x1 &gt; x3$:

In [150]:
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   1   2   6
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0
5  -1   2   1
6   5   5   5

In [151]:

# TODO - Методом DataFrame.query() получить записи, удовлетворяющие условию
#           x1 > x3
df.query('x1 > x3')

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [153]:
# TODO - Сделать аналогичное действие, но уже с помощью условной индексации
df[df['x1']>df['x3']]

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0


Задание 5

Переименуйте индексы и колонки во фрейме

In [154]:

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   3   7   0
B   7   0   0
C   8   7   4
D   5   0   6
E   5   2   7

In [158]:

# TODO - переименуйте индексы [A, C] -> [indA, indC] 
#           и колонки [x1, x3] -> [new1, new3]
df.rename(
    index ={
        'A': 'indA',
        'C': 'indC'
    },
    columns={
        'x1': 'new1',
        'x3': 'new3' 
    },
    inplace = True
)
df

new1  x2  new3
indA     3   7     0
B        7   0     0
indC     8   7     4
D        5   0     6
E        5   2     7

Задание 6

Отфильруйте записи по строке, содержащейся в имени индекса (аргумент like):

In [165]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [166]:
# TODO - отфильтруйте по записям, должны остаться записи, 
#           индекс которых содержит слово "house"
df.filter(regex='house$',axis = 'index')


x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

Задание 7

Отсортируйте данные:

In [176]:

df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df

col1  col2  col3  col4  col5
0     6     4    12    13     9
1    14     3    15     2    18
2    15     0     8     3    14
3     0     3    12     8     5
4     4    19    17     3     5

In [188]:
# TODO - отсортируйте данные индекса 3 по убыванию
df.sort_values(by = 3, axis='columns', ascending=False)

col3  col4  col5  col2  col1
0    12    13     9     4     6
1    15     2    18     3    14
2     8     3    14     0    15
3    12     8     5     3     0
4    17     3     5    19     4


Задание 8

Разделите показатель качества в диапазоне $[0, 100]$ на три группы: плохое $[0-20]$, среднее $(20-45]$, хорошее $(45-85]$, отличное $(85-100]$. Выясните, что происходит со значениями, которые не попадают в диапазоны категорий:

In [205]:
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df['named'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85, 100],
    labels=['плохо', 'среднее', 'хорошее','отличное'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df
#если число не входит не в одну группы, то ему выдается группа NaN

quality     named
0         7     плохо
1        67   хорошее
2        21   среднее
3        38   среднее
4         2     плохо
5        -2       NaN
6        79   хорошее
7        22   среднее
8         5     плохо
9        31   среднее
10       77   хорошее
11       72   хорошее
12       23   среднее
13       64   хорошее
14       99  отличное

Задание 9

Произведите агрегацию средним по рядам

In [206]:
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [210]:
# TODO - произведите агрегацию по рядам (найти среднее)
df.aggregate(['mean'], axis='columns')

mean
0   2.0
1   5.0
2   8.0


Задание 10

Сгруппируйте данные по признаку x2 и найдите медиану и максимальное значения по признакам x1, x3:

In [223]:

df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df

x1      x2  x3
0    89    high  24
1    45    high   5
2    44  medium -20
3    24     low -11
4    45    high  23
..   ..     ...  ..
195  47  medium  18
196  44  medium -19
197  89     low  21
198  13     low  18
199  89     low -12

[200 rows x 3 columns]

In [222]:
# TODO - произведите групировку данных
#           и получите средние и максимальные значения по каждой группе

newdf = df.groupby(by='x2')
newdf.agg(['mean','max'])

x1            x3    
             mean max      mean max
x2                                 
high    57.256098  99  5.097561  28
low     54.018519  98  2.814815  28
medium  55.640625  93  4.937500  29

In [224]:
import string


Задание 11

Разберитесь в аргументах DataFrame.to_csv() и сохраните данные в файл так, чтобы в файл индекс не сохранялся.

In [250]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df

x1  x2  x3
A   9   1   1
B   8   1   3
C   4   3   5
D   1   1   6
E   1   5   3
F   4   5   3
G   4   3   7
H   6   5   2
I   0   4   9
J   7   0   4
K   4   7   9
L   9   7   0
M   8   5   1
N   5   8   6
O   7   7   5

In [251]:
# TODO - сохранить в файл no_index.csv без индексов
df.to_csv('my_first_file.csv',index = False)


In [252]:
dfi = pd.read_csv('my_first_file.csv')
df.head(3)

x1  x2  x3
A   9   1   1
B   8   1   3
C   4   3   5

Задачки

Создайте фрейм с тремя колонками:

Колонка с именами (тип - объекты);
Колонка с стажем работы (тип - вещественный);
Колонка с возрастом (тип - целочисленный);
Колонка с названием любимого цвета (тип - категориальный);
Имена колонок и значения любые, не менее трех записей (строк) в фрейме.

In [262]:

# TODO - создайте фрейм и настройте правильные типы колонок
#           DataFrame.info() дожен отображать указанные типы
df = pd.DataFrame({
    'имена': ['Коля','Леша','Никита'],
    'стаж работы': [10*np.random.random(),10*np.random.random(),10*np.random.random()],
    'возраст': [int(10*np.random.random()),int(10*np.random.random()),int(10*np.random.random())],
    'любимый_цвет': pd.Categorical(["синий","синий","синий"])
}
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   имена         3 non-null      object  
 1   стаж работы   3 non-null      float64 
 2   возраст       3 non-null      int64   
 3   любимый_цвет  3 non-null      category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 291.0+ bytes


Выберите числа в ряду ds1, которых нет в ряду ds2:

Почитайте и примение метод Series.isin()

In [263]:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])

# TODO - выберите значения в ds1, которых нет в ds2: 
# [2, 3]

In [269]:
ds1[~ds1.isin(ds2)]


1    2
2    3
dtype: int64


Оставьте в ряду два наиболее частых значения, остальные замените значением 'Другое':

In [288]:
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])

# TODO - определите два наиболее частых значения в ряду (1, 4),
#           остальные замените значением 'Другое'
# ['Другое', 'Другое', 'Другое', 4, 4, 4, 'Другое', 1, 1, 1, 1, 4]
ds.replace(ds.value_counts()[~(max(ds.value_counts()) == ds.value_counts())].index,'Другое')

0     Другое
1     Другое
2     Другое
3          4
4          4
5          4
6     Другое
7          1
8          1
9          1
10         1
11         4
dtype: object


Сделайте каждую первую букву в словах ряда заглавной:

In [306]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

# TODO - сделайте каждую первую букву заглавной с помощью Series.apply()
def makeBig(words):
  return words.title()
ds.apply(makeBig)

0        How
1         To
2        Use
3    Pandas?
dtype: object


Выберите записи с максимальным значением по колонке x1:

In [311]:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# TODO - выберите те записи, которые имеют x1 равный 
#           максимальному значению в колонке x1
df

x1  x2  x3
0    0   0   0
1    2   2   1
2    3   0   0
3    0   1   0
4    1   2   2
5    2   3   3
6    0   3   3
7    1   3   3
8    3   0   0
9    0   3   3
10   3   1   0
11   2   0   2
12   3   1   3
13   2   3   2
14   2   3   0

In [314]:
df[df['x1'] == max(df['x1'])]

x1  x2  x3
2    3   0   0
8    3   0   0
10   3   1   0
12   3   1   3


Выведите количество пропусков в каждой колонке данных:

In [316]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df

Manufacturer    Model     Type  ...  Weight   Origin                Make
0         Acura  Integra    Small  ...  2705.0  non-USA       Acura Integra
1           NaN   Legend  Midsize  ...  3560.0  non-USA        Acura Legend
2          Audi       90  Compact  ...  3375.0  non-USA             Audi 90
3          Audi      100  Midsize  ...  3405.0  non-USA            Audi 100
4           BMW     535i  Midsize  ...  3640.0  non-USA            BMW 535i
..          ...      ...      ...  ...     ...      ...                 ...
88   Volkswagen  Eurovan      Van  ...  3960.0      NaN  Volkswagen Eurovan
89   Volkswagen   Passat  Compact  ...  2985.0  non-USA   Volkswagen Passat
90   Volkswagen  Corrado   Sporty  ...  2810.0  non-USA  Volkswagen Corrado
91        Volvo      240  Compact  ...  2985.0  non-USA           Volvo 240
92          NaN      850  Midsize  ...  3245.0  non-USA           Volvo 850

[93 rows x 27 columns]

In [318]:
# TODO - отобразите количество пропусков в данных по каждой колонке
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Замените пропущенные значения в колонке Min.Price средним значениям по этой колонке:

In [322]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

# TODO - заполните NaN в колонке Min.Price средним значением по этой колонке
# NOTE - после заполнения убедитесь, что в этой колонке нет пропущенных
df

Manufacturer    Model     Type  ...  Weight   Origin                Make
0         Acura  Integra    Small  ...  2705.0  non-USA       Acura Integra
1           NaN   Legend  Midsize  ...  3560.0  non-USA        Acura Legend
2          Audi       90  Compact  ...  3375.0  non-USA             Audi 90
3          Audi      100  Midsize  ...  3405.0  non-USA            Audi 100
4           BMW     535i  Midsize  ...  3640.0  non-USA            BMW 535i
..          ...      ...      ...  ...     ...      ...                 ...
88   Volkswagen  Eurovan      Van  ...  3960.0      NaN  Volkswagen Eurovan
89   Volkswagen   Passat  Compact  ...  2985.0  non-USA   Volkswagen Passat
90   Volkswagen  Corrado   Sporty  ...  2810.0  non-USA  Volkswagen Corrado
91        Volvo      240  Compact  ...  2985.0  non-USA           Volvo 240
92          NaN      850  Midsize  ...  3245.0  non-USA           Volvo 850

[93 rows x 27 columns]

In [323]:
df['Min.Price'].fillna(df['Min.Price'].mean())

0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64

Отсортируйте и выведите фрейм с колонками в алфавитном порядке:

In [324]:

df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))

# TODO - получите фрейм с отсортированными по именам колонкам (f e d c b a)
# NOTE - сортировка должна быть автоматической
df

f  b  e  c  d  a
0  1  9  8  4  1  0
1  9  1  4  3  7  2
2  5  0  0  2  0  7
3  7  3  8  3  0  6
4  6  1  0  7  6  4

In [338]:
df.reindex(sorted(df.columns,reverse=True),axis=1)

f  e  d  c  b  a
0  1  8  1  4  9  0
1  9  4  7  3  1  2
2  5  0  0  2  0  7
3  7  8  0  3  3  6
4  6  0  6  7  1  4

Отобразите каждую 20ю запись во фрейме и только колонки Manufacturer, Model, Type:

In [342]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

# TODO - отобразите запись с периодичностью во фрейме и определенные колонки
df.loc[::20,['Manufacturer','Model','Type']]


Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

Получите ряд, который содержит длины строк:

In [344]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

# TODO - создайте ряд, содержащий длины строк:
# 0    3
# 1    2
# 2    3
# 3    7
# dtype: int64
ds.str.len()

0    3
1    2
2    3
3    7
dtype: int64